### ISSUE TITLE
lableOn and labelOff do not work with other string values 

### ISSUE THREAD

**Issue by KERNELPANlC** [UncommonConcept/ngx-toggle-switch#4]
When using labelOn="Show" or LabelOff="Hide" or any string such as "On" or "off" the default values "yes" or "no" displayed on the toggle switch.

**Comment by samuelslf** [comment]
Hei @VEfremovski, I did a pull request with an update to the evolution of functionality.

**Comment by codinronan** [comment]
Hi there, this was addressed in #5 , I couldn't actually merge that PR directly because I rebased on the upstream, but this is now fixed.

I have also brought this repo up to date with the upstream repo, so it brings in all the AOT, NG5, bugfix goodies. Please note, the new version builds on Angular 5, hopefully you can update.

By the way the new version is now also published to NPM:
https://www.npmjs.com/package/ngx-toggle-switch
